---
title: "Introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  fig.height=4, 
  fig.width=7
)
```

## Visualizing draws from the prior

```{r prior}
set.seed(1982)
library(IMPosterior)
IMPosterior(prior = rnorm(n = 100000, mean = 0, sd = 1))
```

## Visualizing draws from the posterior

```{r posterior}
IMPosterior(posterior = rnorm(n = 100000, mean = 0.75, sd = 0.5))
```

## Transition from the prior to the posterior

```{r transition}
IMPosterior(prior = rnorm(n = 100000, mean = 0, sd = 1),
            posterior = rnorm(n = 100000, mean = 0.75, sd = 0.5))
```

## Setting to Meanimun Meaningful Effect

```{r MME}
IMPosterior(prior = rnorm(n = 100000, mean = 0, sd = 1),
            posterior = rnorm(n = 100000, mean = 0.75, sd = 0.5), 
            MME = 0.25)
```

## Setting a Threshold for Decision Making

```{r threshold}
IMPosterior(prior = rnorm(n = 100000, mean = 0, sd = 1),
            posterior = rnorm(n = 100000, mean = 0.75, sd = 0.5), 
            MME = 0.25, 
            threshold = 0.7)
```

## Setting the units

```{r units}
IMPosterior(prior = rnorm(n = 100000, mean = 0, sd = 1),
            posterior = rnorm(n = 100000, mean = 0.75, sd = 0.5), 
            MME = 0.25, 
            threshold = 0.7, 
            units = "standard deviations")
```

## Setting the colors

```{r colors}
IMPosterior(prior = rnorm(n = 100000, mean = 0, sd = 1),
            posterior = rnorm(n = 100000, mean = 0.75, sd = 0.5), 
            MME = 0.25, 
            threshold = 0.7, 
            units = "standard deviations", 
            colors = c("#e9a3c9", "#f1a340", "#a1d76a"))
```
